name: CD

on:
  # workflow_run:
  #   workflows: ["CI"]
  #   types:
  #   - completed
  repository_dispatch:
    types: [ci_passed]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Hello
      run: echo "Hello world from CD"

    - name: Modify the helm values
      run: echo "Image is ${{ github.event.client_payload.image }}"
  
